### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/Stargate-Bukkit#29]
Ensure that all features are working now that the 1.17 API has been released.
Possible changes that might break stuff are as follows: (ticked if harmless)

- [x] Copper changes states unless waxed
- [x] Glowing signs exist... not sure how those will work with portals.
- [x] Y axis can now reach values of N; can be:
   - [x]  positive
   - [x]  negative
- [x] Slabs is now a block type.
- [x] We now need to use java 16

**Comment by Thorinwasher** [comment]
Seems to be working normally
