### ISSUE TITLE
Improve Bstats Integration

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/Stargate-Bukkit#30]
Currently, bstats reports minimal information.
Reporting more data would be helpful in informing the rewrite.

Possible subjects could include:
- Number of gates on the server.
- What options (flags) are in use.
- If bungee portals are in use.
- Number of gate designs (`.gate`) files.
- Number of underwater portals on the server.
- Whether economy support is enabled.
- Selected language.
- Default gate network.

**Comment by Thorinwasher** [comment]
Nothing works
