### ISSUE TITLE
Support Bukkit Tags

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/Stargate-Bukkit#31]
Now that Slabs are a Tag, it should be possible to greatly simplify the `.gate` file process.
This will be particularly useful with portal packs.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html

**Comment by Thorinwasher** [comment]
Implemented in commit https://github.com/the-lockedcraft-legacy-organization/Stargate-Bukkit/commit/ca921e6f3972b50a8f0a7350f2a52d0a14a838d8

Happy 300 commit anniversary !!!
